export const API = {
  auth: {
    me: "/auth/me",
    login: "/auth/login",
    register: "/auth/register",
    refresh: "/auth/refresh",
    changePassword: "/auth/change-password",
    logout: "/auth/logout",
    users: "/users",
    userById: (id: string) => `/users/${id}`,
    userMe: "/users/me",
    userMeEmail: "/users/me/email",
    userMePhone: "/users/me/phone",
    activateUser: (id: string) => `/users/${id}/activate`,
  },
  reading: {
    admin: "/api/reading-admin",
    student: "/api/reading-student",
    adminList: "/api/reading-admin/reading-list",
    adminById: (id: string) => `/api/reading-admin/${id}`,
    adminQuestionsCount: (id: string) => `/api/reading-admin/${id}/questions/count`,
    studentById: (id: string) => `/api/reading-student/${id}`,
  },
  messages: {
    base: "/api/messages",
    byId: (id: string) => `/api/messages/${id}`,
    replies: (id: string) => `/api/messages/${id}/replies`,
    replyById: (messageId: string, replyId: string) => `/api/messages/${messageId}/replies/${replyId}`,
    reactions: (id: string) => `/api/messages/${id}/reactions`,
  },
  achievement: {
    base: "/api/achievement",
    myAchievements: "/api/achievement/achievements/me",
    userAchievements: (userId: string) => `/api/achievement/users/${userId}/achievements`,
    publicAchievements: (userId: string) => `/api/achievement/achievements/${userId}/public`,
    completedAchievements: (userId: string) => `/api/achievement/achievements/${userId}/completed`,
    featured: (id: string, showcased: boolean) => `/api/achievement/achievements/featured/${id}?showcased=${showcased}`,
    studentProgress: (userId: string) => `/api/achievement/student-progress/${userId}`,
    studentScore: (userId: string) => `/api/achievement/student-progress/${userId}/score`,
    studentMissions: (userId: string) => `/api/achievement/student-progress/${userId}/missions`,
    claimMission: (userId: string, missionId: string) => (
      `/api/achievement/student-progress/${userId}/missions/${missionId}/claim`
    ),
    adminAchievements: "/api/achievement/admin/achievements",
    adminAchievementById: (id: string) => `/api/achievement/admin/achievements/${id}`,
    adminDailyMissions: "/api/achievement/admin/daily-missions",
    adminDailyMissionById: (id: string) => `/api/achievement/admin/daily-missions/${id}`,
  },
  clan: {
    base: "/api/clan",
    list: "/api/clan/list",
    detail: (id: string) => `/api/clan/detail/${id}`,
    create: "/api/clan/create",
    edit: "/api/clan/edit",
    delete: (id: string) => `/api/clan/delete/${id}`,
    addMember: (id: string) => `/api/clan/${id}/add-member`,
    editMember: (id: string, index: string) => `/api/clan/${id}/edit-member/${index}`,
    deleteMember: (id: string, index: string) => `/api/clan/${id}/delete-member/${index}`,
  },
  authSession: "/api/auth-session",
  authProxy: "/api/auth-proxy",
} as const;
